# Generated by Django 5.0.1 on 2024-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0002_rename_puissance_appareil_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsinternaute',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informationsinternaute',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informationsinternaute',
            name='town',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='informationsinternaute',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='informationsinternaute',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='informationsinternaute',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
