# Generated by Django 5.0.1 on 2024-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0003_informationsinternaute_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsinternaute',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationsinternaute',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationsinternaute',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
